id: 456338d1b6ea43c5b7e7bbca3c512d50
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_196-The_Dwelling_Place_of_Manjusri-v2
  language: bo
  author: ''
  volume: {}
